id: P007117
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG23085
  title: སྐད་ཡིག་ཉེར་མཁོ་ཤེས་བྱ་སྣང་བྱེད་སྒྲོན་མེ།
  author: ''
  volumes:
    29eb55cc26eb41358ada58f4abafde64:
      image_group_id: I1KG23194
      title: ''
      volume_number: 1
      total_pages: 388
ebook_metadata:
  title: སྐད་ཡིག་ཉེར་མཁོ་ཤེས་བྱ་སྣང་བྱེད་སྒྲོན་མེ།
  author: ''
  sku: P007117
  cover: cover.jpg
  layers:
  - pagination
