id: P007117
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG23085
  title: སྐད་ཡིག་ཉེར་མཁོ་ཤེས་བྱ་སྣང་བྱེད་སྒྲོན་མེ།
  author: ''
  volumes:
    92c09fe83c0d4d88918ad12b4067bca8:
      image_group_id: I1KG23194
      title: Volume 1 of skad yig nyer mkho shes bya snang byed sgron me/
      volume_number: 1
      total_pages: 388
      base_file: v001.txt
