id: opecha:P007117
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG23085
  title: སྐད་ཡིག་ཉེར་མཁོ་ཤེས་བྱ་སྣང་བྱེད་སྒྲོན་མེ།
  volume:
    92c09fe83c0d4d88918ad12b4067bca8:
      image_group_id: I1KG23194
      title: Volume 1 of skad yig nyer mkho shes bya snang byed sgron me/
      volume_number: 1
      total_pages: 388
  author: ''
ebook_metadata:
  title: སྐད་ཡིག་ཉེར་མཁོ་ཤེས་བྱ་སྣང་བྱེད་སྒྲོན་མེ།
  author: ''
  sku: P007117
  cover: cover.jpg
  layers:
  - pagination
