id: ICC4311E4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T20:02:32+00:00'
last_modified: '2022-06-09T05:38:03.999699+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG23085
  title: སྐད་ཡིག་ཉེར་མཁོ་ཤེས་བྱ་སྣང་བྱེད་སྒྲོན་མེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    A698:
      image_group_id: I1KG23194
      title: Volume 1 of skad yig nyer mkho shes bya snang byed sgron me/
      total_pages: 388
      order: 1
      base_file: A698.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
